### ISSUE TITLE
add id to <td>

### ISSUE THREAD

**Issue by gfldex** [perl6/modules.perl6.org#53]
e.g.
<td class="name" id="Acme::Meow"> [...] Acme::Meow</td>

That would allow linking from a README.md to the module in the ecosystem if that module is a dependency or for general propaganda.

**Comment by zoffixznet** [comment]
Why not link to a search query? Like [http://modules.perl6.org/#q=Adventure::Engine](http://modules.perl6.org/#q=Adventure%3A%3AEngine). And if you wish to link to a README, just link to the repo with [http://modules.perl6.org/repo/Adventure::Engine](http://modules.perl6.org/repo/Adventure::Engine)

---

A definite :-1: from me due to it not being effective means for the wished purpose and due to it adding more markup to an already heavy page.

For example, here's what accessing a link to `Adventure::Engine` would look like. 
![link1](https://cloud.githubusercontent.com/assets/5747918/12292964/6431b186-b9be-11e5-9c83-43440b06cb29.png)

And here's what a link to `Zef` would look like (note, it's not at the top).
![link2](https://cloud.githubusercontent.com/assets/5747918/12292970/6962488c-b9be-11e5-93d9-dc956bb5bc5a.png)

You could style `:target` pseudo-class, but even then it would not be effective, since the user clicking a link isn't expecting a wall of modules.
