### ISSUE TITLE
Check for Appveyor.yml for windows CI

### ISSUE THREAD

**Issue by szabgab** [perl6/modules.perl6.org#76]
If possible also display the status of the Windows build.

**Comment by briandfoy** [comment]
You also need to check for .appveryor.yml. For instance, my PrettyDump module has that filename and is tested on AppVeyor but does not show such on modules.perl6.org.

**Comment by briandfoy** [comment]
Pull request #77 sent.

But when I tested locally, it still reported PrettyDump as "unknown" even though the last status is "passing".

**Comment by zoffixznet** [comment]
> But when I tested locally, it still reported PrettyDump as "unknown" even though the last status is "passing".

At the moment it reports all statuses as `unknown`. A PostProcessor to actually fetch the status from AppVeyor's API still needs to be implemented: https://irclog.perlgeek.de/perl6/2017-08-02#i_14957533

**Comment by briandfoy** [comment]
I've started a processor and sent PR #78. Don't merge it blindly though!

**Comment by zoffixznet** [comment]
PR merged however for some mystery reason the app should've mentioned doing appveyor stuff in the log (I'm tailing the current run) but it doesn't, despite the git log showing it got all the recent commits.

I ran a local copy of the site and the appveyor stuff worked but the API URL was a 404. I [managed to fix that](https://github.com/perl6/modules.perl6.org/commit/221988d0f6) by adding a recordsNumber param and locally the appveyor now works.

The last build on live site is currently at `Processing dist 461 of 867`. After it finishes it should fetch my commit and rebuild everything again and I hope whatever that mystery reason is will be gone and appveyor will work.

![untitled](https://user-images.githubusercontent.com/5747918/28947527-61543b16-787e-11e7-997f-66486ca7f018.png)

**Comment by zoffixznet** [comment]
No love. It still fails to print in the log that it's doing a full rebuild. I now [made the shell script always use full rebuild](https://github.com/perl6/modules.perl6.org/commit/86dddb247fda06c333094acf98f4e9ddee9a500f) to see if that fixes anything. Gonna dig into this more tomorrow.

**Comment by zoffixznet** [comment]
I killed everything, undid the always-rebuild, and it magically started working.

I now see AppVeyor status on the live site,, so this issue is now resolved. Thanks all.

**Comment by briandfoy** [comment]
Thanks everyone!

**Comment by szabgab** [comment]
🍪 🍰 🍷

**Comment by szabgab** [comment]
Hmm, the strange thing is that the number of modules that have Appveyor configured  (reported in the text at the top of http://modules.perl6.org/ ) went down from 40 to 38 since yesterday. Are maybe the 'unknown' reports marked as 'not set up' now?

**Comment by zoffixznet** [comment]
> 'unknown' reports marked as 'not set up' now

Yeah, that's it. I managed to repro it locally too. On full rebuild it gets logged as `unknown`, but when going through the "cached" update it gets changed to not set up.

I'm guessing `$dist->{_builder}{has_appveyor}` doesn't always get correctly set and so the status gets tossed [on this line](https://github.com/perl6/modules.perl6.org/blob/160e2ced4731cc7783c05bd751f1b4aa61d40541/lib/ModulesPerl6/DbBuilder/Dist/PostProcessor/AppVeyor.pm#L25-L28).

I'll fix it after work, in about 12 hours.

**Comment by zoffixznet** [comment]
OK, I'm re-opening this Issue, as I found a problem I don't know a solution for.

First, the `unknown` stuff mentioned above along with several other issues, including yesterday's mystery problem, [was fixed in a bunch of commits made today](https://github.com/perl6/modules.perl6.org/compare/160e2ce...c475659). The site now shows appveyor statuses for 53 instead of 38 dists.

However, turns out the `github-username/github-repo-name` do not map exactly to appveyor's `username/projectname` (e.g. [this](https://github.com/ugexe/Perl6-Net--HTTP) module name doesn't have an extra hyphen [on appveyor](https://ci.appveyor.com/project/ugexe/Perl6-Net-HTTP/branch/master) and [this one](https://github.com/sergot/openssl) has a different username [on appveyor](https://ci.appveyor.com/project/skinkade/openssl/branch/master)).

For fetching the build status itself, I managed to [work around](https://github.com/perl6/modules.perl6.org/commit/2ee3f47d16e3c579b5169d4e14858ac530c2fd0e) that problem by fetching an SVG badge and parsing it. The badge URL has special feature that you can use `github/` in the URL to indicate the user/repo names are that of a GitHub repo.

I googled around for some sort of the same feature to get the project page we can link the status link to, but [appveyor's staff in January said](http://help.appveyor.com/discussions/questions/471-infer-badge-url-from-github-user-repo-name#comment_41730781) that feature isn't available.

I tried dumping headers from the status badges and looking at API docs, but I don't see any way for us to figure out the link to AppVeyor project page, if all we have a is a GitHub repo URL and its contents.

Anyone have any ideas?

**Comment by zoffixznet** [comment]
Fixed it to "good enough" levels:

- Try to fetch status from API using GitHub's user/repo
        for AppVeyor user/slug; if success, that's the AppVeyor url
- If that fails, fetch status from badge and rake repo's README
        for the URL to AppVeyor project and use that
- If that fails, just direct AppVeyor URL to dist repo
